import { begin } from "@/src/selfcheck";
import { cropImage, fullCrop, fullPageImage, localResizeDelta, moveCrop, moveImage, nudgeImage, resizeCrop, resizeImage, rotateImage } from "@/src/image-geometry";
const finish = begin();
const image = fullPageImage();
console.assert(moveImage(image, -12, 7).box.x === -12, "an image can move beyond the page");
console.assert(resizeImage(image, "se", 20, 20).box.w === 120, "corner resize expands the image element");
console.assert(resizeImage(image, "e", 20, 0, true).box.w === 120, "shift resize can stretch one axis");
const east = resizeImage(image, "e", 20, 0);
console.assert(east.box.x === 0 && east.box.w === 120 && east.box.y === -10 && east.box.h === 120, "east handle anchors its opposite edge and centres proportional height");
const northWest = resizeImage(image, "nw", 20, 20);
console.assert(northWest.box.x === 20 && northWest.box.y === 20 && northWest.box.w === 80 && northWest.box.h === 80, "corner resize anchors the opposite corner");
const stretchedNorth = resizeImage(image, "n", 0, 20, true);
console.assert(stretchedNorth.box.y === 20 && stretchedNorth.box.h === 80 && stretchedNorth.box.w === 100, "shift on an edge stretches just that axis");
console.assert(nudgeImage(image, "left", 5).box.x === -5, "keyboard nudge moves the image without changing its size");
console.assert(rotateImage(image, -15).box.rotation === 345, "rotation is normalised for stable rendering");
const local = localResizeDelta(rotateImage(image, 90), 0, 10);
console.assert(Math.round(local.dx) === 10 && Math.round(local.dy) === 0, "resize uses the image's local axes after rotation");
const cropped = cropImage(image, { left: .1, top: .2, right: .8, bottom: .9 });
console.assert(cropped.crop?.left === .1 && cropped.crop?.bottom === .9, "crop belongs to the image element");
const clampedCrop = moveCrop(cropped.crop!, 2, -2);
console.assert(Math.abs(clampedCrop.left - .3) < .000001 && clampedCrop.top === 0, "crop movement remains inside its source image");
console.assert(resizeCrop(fullCrop(), "nw", .2, .2).left === .2, "crop handles edit the source crop rather than the page frame");
finish("image-geometry.test.ts");
